# Generated by Django 4.0.3 on 2024-03-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='password',
            new_name='grad',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='username',
            new_name='major',
        ),
    ]
