# Generated by Django 4.0.3 on 2024-03-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='password',
        ),
        migrations.RemoveField(
            model_name='form',
            name='username',
        ),
        migrations.AddField(
            model_name='form',
            name='firstname',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='gradyear',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='lastname',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='major1',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='major2',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='minor1',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='minor2',
            field=models.TextField(default='0000000', editable=False),
        ),
        migrations.AddField(
            model_name='form',
            name='startyear',
            field=models.TextField(default='0000000', editable=False),
        ),
    ]
